export const FETCHING_DRIVERS = 'FETCHING_DRIVERS';
export const FETCHING_DRIVERS_SUCCESS = 'FETCHING_DRIVERS_SUCCESS';
export const FETCHING_DRIVERS_FAILURE = 'FETCHING_DRIVERS_FAILURE';

export const FETCHING_LICENCETYPES = 'FETCHING_LICENCETYPES';
export const FETCHING_LICENCETYPE = 'FETCHING_LICENCETYPE';
export const FETCHING_LICENCETYPE_SUCCESS = 'FETCHING_LICENCETYPE_SUCCESS';
export const FETCHING_LICENCETYPES_SUCCESS = 'FETCHING_LICENCETYPES_SUCCESS';
export const FETCHING_LICENCETYPES_FAILURE = 'FETCHING_LICENCETYPES_FAILURE';

export const FETCHING_VEHICLETYPES = 'FETCHING_VEHICLETYPES';
export const FETCHING_VEHICLETYPE = 'FETCHING_VEHICLETYPE';
export const FETCHING_VEHICLETYPES_SUCCESS = 'FETCHING_VEHICLETYPE_SUCCESS';
export const FETCHING_VEHICLETYPES_FAILURE = 'FETCHING_VEHICLETYPES_SUCCESS';
export const FETCHING_VEHICLETYPE_SUCCESS = 'FETCHING_VEHICLETYPES_FAILURE';

export const FETCHING_CONTAINERTYPES = 'FETCHING_CONTAINERTYPES';
export const FETCHING_CONTAINERTYPES_SUCCESS = 'FETCHING_CONTAINERTYPES_SUCCESS';
export const FETCHING_CONTAINERTYPES_FAILURE = 'FETCHING_CONTAINERTYPES_FAILURE';
export const FETCHING_CONTAINERTYPE = 'FETCHING_CONTAINERTYPE';
export const FETCHING_CONTAINERTYPE_SUCCESS = 'FETCHING_CONTAINERTYPE_SUCCESS';

export const FETCHING_CARBRANDS = 'FETCHING_CARBRANDS';
export const FETCHING_CARBRANDS_SUCCESS = 'FETCHING_CARBRANDS_SUCCESS';
export const FETCHING_CARBRANDS_FAILURE = 'FETCHING_CARBRANDS_FAILURE';
export const FETCHING_CARBRAND = 'FETCHING_CARBRAND';
export const FETCHING_CARBRAND_SUCCESS = 'FETCHING_CARBRAND_SUCCESS';

export const FETCHING_WASTEMANAGEMENTS = 'FETCHING_WASTEMANAGEMENTS';
export const FETCHING_WASTEMANAGEMENTS_SUCCESS = 'FETCHING_WASTEMANAGEMENTS_SUCCESS';
export const FETCHING_WASTEMANAGEMENTS_FAILURE = 'FETCHING_WASTEMANAGEMENTS_FAILURE';
export const FETCHING_WASTEMANAGEMENT = 'FETCHING_WASTEMANAGEMENT';
export const FETCHING_WASTEMANAGEMENT_SUCCESS = 'FETCHING_WASTEMANAGEMENT_SUCCESS';

export const FETCHING_WASTEPLACES = 'FETCHING_WASTEPLACES';
export const FETCHING_WASTEPLACES_SUCCESS = 'FETCHING_WASTEPLACES_SUCCESS';
export const FETCHING_WASTEPLACES_FAILURE = 'FETCHING_WASTEPLACES_FAILURE';
export const FETCHING_WASTEPLACE = 'FETCHING_WASTEPLACE';
export const FETCHING_WASTEPLACE_SUCCESS = 'FETCHING_WASTEPLACE_SUCCESS';

export const FETCHING_STATICCONTAINERS = 'FETCHING_STATICCONTAINERS';
export const FETCHING_STATICCONTAINERS_SUCCESS = 'FETCHING_STATICCONTAINERS_SUCCESS';
export const FETCHING_STATICCONTAINERS_FAILURE = 'FETCHING_STATICCONTAINERS_FAILURE';
export const FETCHING_STATICCONTAINER = 'FETCHING_STATICCONTAINER';
export const FETCHING_STATICCONTAINER_SUCCESS = 'FETCHING_STATICCONTAINER_SUCCESS';

export const FETCHING_UNITS = 'FETCHING_UNITS';
export const FETCHING_UNITS_SUCCESS = 'FETCHING_UNITS_SUCCESS';
export const FETCHING_UNITS_FAILURE = 'FETCHING_UNITS_FAILURE';
export const FETCHING_UNIT = 'FETCHING_UNIT';
export const FETCHING_UNIT_SUCCESS = 'FETCHING_UNIT_SUCCESS';

export const FETCHING_VEHICLE_YEARS = 'FETCHING_VEHICLE_YEARS';
export const FETCHING_VEHICLE_YEARS_SUCCESS = 'FETCHING_VEHICLE_YEARS_SUCCESS';
export const FETCHING_VEHICLE_YEARS_FAILURE = 'FETCHING_VEHICLE_YEARS_FAILURE';
export const FETCHING_VEHICLE_YEAR = 'FETCHING_VEHICLE_YEAR';
export const FETCHING_VEHICLE_YEAR_SUCCESS = 'FETCHING_VEHICLE_YEAR_SUCCESS';





